version: '3.8'

services:

  app:
    build:
      context: ./server
      target: dev
    image: $$DOCKER_HUB_USERNAME/app:latest  # Экранирование $
    environment:
      - MONGO_URI=mongodb://admin:password@mongo:27017/subscriptions?authSource=admin
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongo

  app-test:
    build:
      context: ./server
      target: test
    image: $$DOCKER_HUB_USERNAME/app-test:latest  # Экранирование $
    environment:
      - NODE_ENV=test
      - MONGO_URI=mongodb://admin:password@mongo-test:27017/subscriptions_test?authSource=admin
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongo-test

  nginx:
    image: nginx:latest
    environment:
      API_BACKEND_URL: http://app:4000
    volumes:
      - ./client/dist:/var/www/html
      - ./nginx/conf.d:/etc/nginx/conf.d
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - app

  mongo:
    image: $$DOCKER_HUB_USERNAME/mongo:latest  # Экранирование $
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_data:/data/db

  mongo-test:
    image: $$DOCKER_HUB_USERNAME/mongo-test:latest  # Экранирование $
    ports:
      - "27038:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password
    volumes:
      - mongodb_test_data:/data/db

  client-builder:
    build:
      context: ./client
      target: build
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://app:4000
    image: $$DOCKER_HUB_USERNAME/client-builder:latest  # Экранирование $
    command: npm run build
    container_name: devops_client_build
    volumes:
      - ./client/dist:/app/dist

  client-test:
    build:
      context: ./client
      target: test
      dockerfile: Dockerfile
      args:
        - VITE_API_URL=http://app:4000
    image: $$DOCKER_HUB_USERNAME/client-test:latest  # Экранирование $
    command: npm run test

volumes:
  mongodb_data:
  mongodb_test_data:
