version: '3.8'

services:

  app:
    build:
      context: ./server
      target: dev
    image: $$DOCKER_HUB_USERNAME/app:latest  # Экранирование $
    environment:
      - MONGO_URI=mongodb://admin:password@mongo:27017/subscriptions?authSource=admin
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - mongo

  app-test:
    build:
      context: ./server
      target: test
    image: $$DOCKER_HUB_USERNAME/app-test:latest  # Экранирование $
    environment:
      - NODE_ENV=test
      - MONGO_URI=mongodb://admin:password@mongo-test:27017/subscriptions_test?auth
