version: '3.8'

services:
  app:
    build:
      context: ./server
      target: prod
    environment:
      - NODE_ENV=production
      - MONGO_URI=${MONGO_PROD_URI}
    restart: always

  nginx:
    build:
      context: .
      dockerfile: nginx/Dockerfile
    ports:
      - "80:80"
    depends_on:
      - app