version: '3.8'

services:
  app:
    build:
      context: ./server
      target: test
    environment:
      - NODE_ENV=test
      - MONGO_URI=${MONGO_URI}
    depends_on:
      mongodb:
        condition: service_healthy

  mongodb:
    image: mongo:6.0
    ports:
      - "27017:27017"
    environment:
      MONGO_INITDB_ROOT_USERNAME: admin
      MONGO_INITDB_ROOT_PASSWORD: password