name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_PROJECT_NAME: devops
  MONGO_URI: mongodb://admin:password@mongodb:27017/subscriptions?authSource=admin

jobs:
  build:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: password
        options: --health-cmd "mongo --eval 'db.runCommand(\"ping\").ok'" --health-interval 5s --health-timeout 2s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Build and start services
        run: |
          docker-compose -f docker-compose.yml up -d --build client-builder
          docker-compose -f docker-compose.yml build app nginx

      - name: Verify containers
        run: |
          docker ps -a
          docker-compose logs

  test:
    runs-on: ubuntu-latest
    needs: build
    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: password

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Start test environment
        run: |
          docker-compose -f docker-compose.test.yml up -d --build

      - name: Run server tests
        run: |
          docker exec devops_app npm test

      - name: Run client tests
        run: |
          cd client
          npm install
          npm test

      - name: Stop test environment
        if: always()
        run: |
          docker-compose -f docker-compose.test.yml down

  deploy:
    needs: test
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Login to Docker Hub
        if: github.ref == 'refs/heads/main'
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Push images
        if: github.ref == 'refs/heads/main'
        run: |
          docker-compose -f docker-compose.prod.yml push
