name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  DOCKER_BUILDKIT: 1
  COMPOSE_PROJECT_NAME: devops
  MONGO_URI: mongodb://admin:password@mongo:27017/subscriptions?authSource=admin
  MONGO_URI_TEST: mongodb://admin:password@mongo:27017/subscriptions_test?authSource=admin

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Login to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build Docker images
        run: |
          docker-compose -f docker-compose.yml build

      - name: Start services
        run: |
          docker-compose -f docker-compose.yml up -d mongo
          docker-compose -f docker-compose.yml up -d --build client-builder
          docker-compose -f docker-compose.yml up -d app

      - name: Verify containers
        run: |
          docker ps -a
          docker-compose logs app

  test:
    runs-on: ubuntu-latest
    needs: build
    services:
      mongo:
        image: mongo:6.0
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: password
        options: --health-cmd "mongo --eval 'db.runCommand(\"ping\").ok'" --health-interval 5s --health-timeout 2s --health-retries 5

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Run server tests
        env:
          NODE_ENV: test
          MONGO_URI: ${{ env.MONGO_URI_TEST }}
        run: |
          docker-compose run --rm app npm test

      - name: Run client tests
        run: |
          docker-compose run --rm client-builder npm run test

      - name: Cleanup test containers
        if: always()
        run: |
          docker-compose down