name: CI/CD with Docker

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push server image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/app-server:latest -f server/Dockerfile ./server
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/app-server:latest

      - name: Build and push client image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/app-client:latest -f client/Dockerfile ./client
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/app-client:latest

  test:
    runs-on: ubuntu-latest
    needs: build
    services:
      mongo-test:
        image: mongo:6.0
        ports:
          - "27018:27017"
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: password
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run tests inside containers
        run: |
          docker compose -f docker-compose.yml up --abort-on-container-exit --exit-code-from app-test
          docker compose -f docker-compose.yml up --abort-on-container-exit --exit-code-from client-test


  deploy:
    runs-on: ubuntu-latest
    needs: test
    steps:
      - name: Pull and restart containers
        run: |
          ssh user@your-server "docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/app-server:latest && \
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/app-client:latest && \
          docker-compose down && \
          docker-compose up -d"
