name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

env:
  COMPOSE_PROJECT_NAME: subtrack
  MONGO_URI: mongodb://admin:password@mongo:27017/subscriptions?authSource=admin

jobs:
  test:
    runs-on: ubuntu-latest
    services:
      mongodb:
        image: mongo:6.0
        ports:
          - 27017:27017
        env:
          MONGO_INITDB_ROOT_USERNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: password
          MONGO_INITDB_DATABASE: subscriptions_test

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Docker
        uses: docker/setup-buildx-action@v2

      - name: Run tests
        run: |
          docker-compose -f docker-compose.test.yml up --build --abort-on-container-exit
          docker-compose -f docker-compose.test.yml down

  # deploy:
  #   needs: test
  #   if: github.ref == 'refs/heads/main'
  #   runs-on: ubuntu-latest
  #   steps:
  #     - name: Checkout code
  #       uses: actions/checkout@v3

  #     - name: Deploy to production
  #       run: |
  #         docker-compose -f docker-compose.prod.yml up -d --build