name: CI/CD with Docker

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push client image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/app-client:latest -f client/Dockerfile ./client
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/app-client:latest

      - name: Build and push server image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/app-server:latest -f server/Dockerfile ./server
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/app-server:latest

      - name: Build and push nginx image
        run: |
          docker build -t ${{ secrets.DOCKER_HUB_USERNAME }}/nginx:latest -f nginx/Dockerfile ./nginx
          docker push ${{ secrets.DOCKER_HUB_USERNAME }}/nginx:latest

  test:
    runs-on: ubuntu-latest
    needs: build
    services:
      mongo-test:
        image: mongo:6.0
        ports:
          - "27018:27017"
        env:
          MONGO_INITDB_ROOT_rootNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: password
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run tests inside containers
        run: |
          docker compose -f docker-compose.yml up app-test mongo-test  --abort-on-container-exit --exit-code-from app-test


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up SSH key for Ansible
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run Ansible Playbook to install Docker
        run: |
          ansible-playbook -i ansible/inventory ansible/ansible-playbook.yml


      - name: SSH to the production server and deploy the Docker images
        run: |
          ssh -o StrictHostKeyChecking=no devops@89.169.174.217 "
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_PASSWORD }} && \
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/app-client:latest && \
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/app-server:latest && \
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/nginx:latest && \
          docker-compose -f /path/to/your/docker-compose.yml down && \
          docker-compose -f /path/to/your/docker-compose.yml up -d
          "