name: CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install server & client
        run: |
          cd server
          npm install
          cd ../client
          npm install

      - name: Build server
        run: |
          cd server
          echo "No build needed for pure JS"

      - name: Build client
        run: |
          cd client
          npm run build

  test:
    runs-on: ubuntu-latest
    needs: build   # тесты выполнятся после успешного build
    steps:
      - name: Check out
        uses: actions/checkout@v3
      - name: Use Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 16

      - name: Install server & client
        run: |
          cd server
          npm install
          cd ../client
          npm install

      - name: Test server
        run: |
          cd server
          npm test

      - name: Test client
        run: |
          cd client
          npm test
