name: CI/CD with Docker

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2

      - name: Log in to Docker Hub
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_HUB_USERNAME }}
          password: ${{ secrets.DOCKER_HUB_TOKEN }}

      - name: Build and push Docker Compose services
        run: |
          docker compose -f docker-compose.yml build
          docker compose -f docker-compose.yml push

  test:
    runs-on: ubuntu-latest
    needs: build
    services:
      mongo-test:
        image: mongo:6.0
        ports:
          - "27018:27017"
        env:
          MONGO_INITDB_ROOT_rootNAME: admin
          MONGO_INITDB_ROOT_PASSWORD: password
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Run tests inside containers
        run: |
          docker compose -f docker-compose.yml up app-test mongo-test  --abort-on-container-exit --exit-code-from app-test


  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Check out repository
        uses: actions/checkout@v3

      - name: Set up SSH key for Ansible
        uses: webfactory/ssh-agent@v0.5.3
        with:
          ssh-private-key: ${{ secrets.SSH_PRIVATE_KEY }}

      - name: Run Ansible Playbook to install Docker
        run: |
          ansible-playbook -i ansible/inventory ansible/ansible-playbook.yml

      - name: SSH to the production server and deploy the Docker image
        run: |
          ssh -o StrictHostKeyChecking=no devops@89.169.174.217 "
          docker login -u ${{ secrets.DOCKER_HUB_USERNAME }} -p ${{ secrets.DOCKER_HUB_TOKEN }} && \
          docker pull ${{ secrets.DOCKER_HUB_USERNAME }}/combined-app:latest && \
          docker run -d -p 80:80 ${{ secrets.DOCKER_HUB_USERNAME }}/combined-app:latest"

